const { Router } = require("express");
const { requireAdmin } = require("../middleware/authMiddleware");
const scraperController = require("../controllers/scraperController");

const router = Router();
router.get("/falabella/products", requireAdmin, scraperController.listFalabella);
router.post("/falabella/sync", requireAdmin, scraperController.syncFalabella);
router.post("/falabella/sync-perfumes", requireAdmin, scraperController.syncPerfumeCatalog);
router.get("/ripley/products", requireAdmin, scraperController.listRipley);
router.post("/ripley/sync", requireAdmin, scraperController.syncRipley);
router.post("/ripley/sync-perfumes", requireAdmin, scraperController.syncRipleyPerfumeCatalog);
router.get("/alisha/products", requireAdmin, scraperController.listAlisha);
router.post("/alisha/sync", requireAdmin, scraperController.syncAlisha);
router.post("/alisha/sync-perfumes", requireAdmin, scraperController.syncAlishaPerfumeCatalog);
router.get("/silk/products", requireAdmin, scraperController.listSilk);
router.post("/silk/sync", requireAdmin, scraperController.syncSilk);
router.post("/silk/sync-perfumes", requireAdmin, scraperController.syncSilkPerfumeCatalog);
router.get("/elite/products", requireAdmin, scraperController.listElite);
router.post("/elite/sync", requireAdmin, scraperController.syncElite);
router.post("/elite/sync-perfumes", requireAdmin, scraperController.syncElitePerfumeCatalog);
router.get("/cosmetic/products", requireAdmin, scraperController.listCosmetic);
router.post("/cosmetic/sync", requireAdmin, scraperController.syncCosmetic);
router.post("/cosmetic/sync-perfumes", requireAdmin, scraperController.syncCosmeticPerfumeCatalog);
router.get("/paris/products", requireAdmin, scraperController.listParis);
router.post("/paris/sync", requireAdmin, scraperController.syncParis);
router.post("/paris/sync-perfumes", requireAdmin, scraperController.syncParisPerfumeCatalog);
router.get("/abc/products", requireAdmin, scraperController.listAbc);
router.post("/abc/sync", requireAdmin, scraperController.syncAbc);
router.post("/abc/sync-perfumes", requireAdmin, scraperController.syncAbcPerfumeCatalog);
router.get("/preunic/products", requireAdmin, scraperController.listPreunic);
router.post("/preunic/sync", requireAdmin, scraperController.syncPreunic);
router.post("/preunic/sync-perfumes", requireAdmin, scraperController.syncPreunicPerfumeCatalog);
router.get("/sync-jobs/:jobId", requireAdmin, scraperController.getSyncJob);

module.exports = router;
